[server]
headless = true
enableCORS = false

[theme]
base = "light"
primaryColor = "#3DB860"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#EBF7F8"
textColor = "#1E7A8C"
font = "sans serif"

[browser]
gatherUsageStats = false
