[server]
headless = true
enableCORS = false

[theme]
base = "light"
primaryColor = "#2DBD6E"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#EDF1FA"
textColor = "#1C2E5E"
font = "sans serif"

[browser]
gatherUsageStats = false
